# Generated by Django 3.2.9 on 2021-11-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DynaForm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='argonaute',
            old_name='name',
            new_name='argo_name',
        ),
    ]
